# Generated by Django 5.2.7 on 2025-10-28 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('phone_num', models.TextField(blank=True, null=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('company', models.TextField(blank=True, null=True)),
                ('job', models.TextField(blank=True, null=True)),
                ('ipv4', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
